
language: php

php:
  - '5.6'

branches:
  only:
    - master

addons:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS 'database';"
  - mysql -e "CREATE USER 'newuser'@'localhost IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL ON *.* TO 'new_user'@'localhost'";
  - mysql -e "FLUSH PRIVILEGES;"

before_script:
  - mkdir -p build/logs
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
    --configuration phpunit.xml
    --bootstrap ./vendor/autoload.php
    --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

notifications:
  email: "bianco@javanile.org"
