version: '3.7'

services:
  php:
    build: .
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t handbook/public handbook/serve.php
    environment:
      - DB_TYPE=pgsql
      - PGSQL_HOST=postgres
      - PGSQL_NAME=postgres
      - PGSQL_USER=postgres
      - PGSQL_PASS=postgres
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
    links:
      - postgres

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    ports:
      - 8081:8080
